export const ActionTypes = {
    //  Counters Actions

    ADD_NEW_COUNTER: "ADD_NEW_COUNTER",
    DELETE_ALL_COUNTERS: "DELETE_ALL_COUNTERS",
    RESET_ALL_COUNTERS: "RESET_ALL_COUNTERS",

    //  Counter Action

    INCREMENT_COUNTER: "INCREMENT_COUNTER",
    DECREMENT_COUNTER: "DECREMENT_COUNTER",
    RESET_COUNTER: "RESET_COUNTER",
    DELETE_COUNTER: "DELETE_COUNTER",
};
